version: '3.0'

services:
  frontend:
    image: todoroff318/testfr:testfr
    container_name: puskankafr
    ports:
      - "8081:8081"
    depends_on:
      - backend

  backend:
    image: todoroff318/test:test
    container_name: puskankabnd
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  data:


