name: Triggered Workflow

on:
  repository_dispatch:
    types: [trigger-uat-event]

  workflow_dispatch:

jobs:
  triggered-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check Dispatch Payload
        run: echo "Triggered by a dispatch event with payload ${{ github.event.client_payload.description }}"

      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set script permissions
        run: chmod +x ./scripts/redeploy.sh

      - name: Start Application
        run: ./scripts/redeploy.sh &

      - name: Log out of Docker Hub
        if: always()
        run: docker logout
